# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{exceptionist}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["alto"]
  s.date = %q{2010-10-15}
  s.description = %q{Request a certain HTTP status code to be returned}
  s.summary = %q{Force your Rails (version >= 3) application to crash}
  s.email = %q{boettger@mt7.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files         = `git ls-files`.split($\)
  s.executables   = s.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
  s.test_files    = s.files.grep(%r{^(test|spec|features)/})
  s.homepage = %q{http://github.com/alto/exceptionist}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}

  s.add_dependency 'activesupport'
  s.add_dependency 'actionpack'

  s.add_development_dependency 'minitest'
  s.add_development_dependency 'shoulda'
  s.add_development_dependency 'turn'

  # if s.respond_to? :specification_version then
  #   current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
  #   s.specification_version = 3

  #   if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
  #     s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  #   else
  #     s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  #   end
  # else
  #   s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  # end
end

